### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by 12people** [groovelauncher/GrooveLauncher#12]
It'd be great to see this launcher on [F-Droid](https://f-droid.org/).

I'm sure it would help a lot of people discover this project!

**Comment by marcellotogg** [comment]
Great to read about it! Thank you very much. 
Any idea when the next release will be?

**Comment by berkaytumal** [comment]
> Great to read about it! Thank you very much. Any idea when the next release will be?

i was in my midterm weak haha it relatively slowed down the development. im back now. I'll try to release it in 2 weeks

**Comment by berkaytumal** [comment]
> It'd be great to see this launcher on [F-Droid](https://f-droid.org/).
> 
> I'm sure it would help a lot of people discover this project!

I'll check the requirements but I think it might create some issues on f-droid. next release will have a small web store that will host some metro style web apps (by me and third parties) maybe I could create a special edition that doesnt have a webstore (very same way how Stremio fixed this issue on iOS devices). and publish that version on play store and f-droid. how does it sound?

**Comment by berkaytumal** [comment]
I opened an issue https://gitlab.com/fdroid/rfp/-/issues/2947 on F-Droid's GitLab
