### ISSUE TITLE
[bug] MIUI contacts app not be recognised?

### ISSUE THREAD

**Issue by KParthSingh** [groovelauncher/GrooveLauncher#17]
Ik live tiles is in it's early stages but i think this is not expected behaviour.

![WhatsApp Image 2024-12-19 at 12 56 04_34a5b467](https://github.com/user-attachments/assets/58df2953-1c1a-4828-94be-bd1d964a5619)

**Comment by berkaytumal** [comment]
whats the package name for your contacts app let me add it to icon pack. (default icon packs and live tiles work in sync)

**Comment by KParthSingh** [comment]
"com.android.contacts/com.android.contacts.activities.PeopleActivity"

**Comment by KParthSingh** [comment]
I forgot to mention also add the dialer package com.android.contacts/com.android.contacts.activities.TwelveKeyDialer

**Comment by KParthSingh** [comment]
You are the best Berkeley!!

**Comment by berkaytumal** [comment]
both dialer and contacts work now?

**Comment by KParthSingh** [comment]
> both dialer and contacts work now?

Yeah
