### ISSUE TITLE
mail apps have the wrong label color

### ISSUE THREAD

**Issue by PF94** [groovelauncher/GrooveLauncher#19]
![Screenshot_20241219_120022_Groove Launcher](https://github.com/user-attachments/assets/ddaa45cf-7311-4af7-9544-18f41c5f33ad)

samsung email and gmail have their icons changed to a white windows metro mail icon, however the label is colored black. afaik this does not happen on any other app with custom windows metro icons, which have white labels.

this is on version 0.5.0-beta5

**Comment by berkaytumal** [comment]
fixed this! thanks for the feedback
