### ISSUE TITLE
Possible draw over status bar? 

### ISSUE THREAD

**Issue by Desideratum11** [groovelauncher/GrooveLauncher#4]
Option to hide status bar and replace with a built in one similar to wp?

**Comment by ollietheotter983** [comment]
And maybe a control center? Custom noti shades/control centers are all over google play so its definitely possible

**Comment by berkaytumal** [comment]
I’m closing this issue because it’s better to make a system-wide change rather than adding it individually for this app. Stay tuned for MetroOS https://discord.gg/x4zEWXY62S
