### ISSUE TITLE
[Feature request] Ability to hide apps from app list.

### ISSUE THREAD

**Issue by KParthSingh** [groovelauncher/GrooveLauncher#5]
As we know OEMs push their apps in android roms and it's not possible to make monochrome icon for every local app or just you do not want to see those OEM apps in app list most of them are bloatware that nobody uses. so, I was thinking what if there was an option below pin to home or uninstall that simply hide the apps from the list and then access those hidden apps in groove settings?

**Comment by berkaytumal** [comment]
yea that would be great!

**Comment by omnitrix9991** [comment]
Hide apps feature would be nice , like hiding banking apps for security purpose .I can open them when I need , but when I share my phone they are hidden .

**Comment by berkaytumal** [comment]
How can users access the hidden applications after?

**Comment by KParthSingh** [comment]
I have this idea that it should be in groove settings behind an option called hidden apps or you can add as an app just like groove settings is.
