### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by marcellotogg** [groovelauncher/GrooveLauncher#7]
I would like to support the project financially, but I don't want to provide my credit card details. Could support via PayPal be integrated into the app?

**Comment by berkaytumal** [comment]
I appreciate your thoughtfulness and interest <3 Regrettably, i'm currently residing in turkey, where PayPal is inexplicably prohibited from usage

**Comment by marcellotogg** [comment]
Ok

Freundliche Grüsse
Marcel Tujetsch

-------- Ursprüngliche Nachricht --------
Am 08.11.24 08:11 um Berkay Tumal schrieb :

**Comment by marcellotogg** [comment]
Unfortunately I am not a programmer, but if you need help translating (en to german or hungarian) contact me.

Regards
Marcel Tujetsch

-------- Ursprüngliche Nachricht --------
Am 10.11.24 17:00 um Berkay Tumal schrieb :
