### ISSUE TITLE
Colouring of the tiles

### ISSUE THREAD

**Issue by marcellotogg** [groovelauncher/GrooveLauncher#8]
For some apps, such as "Proton Mail" the tile is not colored. The name is white and therefore not visible on these tiles (see screenshot).
![Screenshot_2024-11-07-19-00-39-96_993b29805d72aa6239c03931d0ad3a54](https://github.com/user-attachments/assets/5c08d32d-441b-4a9a-a384-6ea48ea250b6)

**Comment by berkaytumal** [comment]
Got it ^^ I’ll fix this in the next update, thanks!

**Comment by marcellotogg** [comment]
Great, thanks

Freundliche Grüsse
Marcel Tujetsch

-------- Ursprüngliche Nachricht --------
Am 08.11.24 08:04 um Berkay Tumal schrieb :

**Comment by marcellotogg** [comment]
Next update received, but the problem already exists!
![Screenshot_2024-11-17-15-38-57-01_993b29805d72aa6239c03931d0ad3a54](https://github.com/user-attachments/assets/968fe415-1537-48e4-96a6-570691867ddf)

**Comment by berkaytumal** [comment]
Sorry for the typo; I’ll correct it in the next minor update (0.5.0).

By the way, I launched the Crowdin project to localize the app. As of now, we’ve translated:
- Azerbaijani (completely)
- Dutch (completely)
- French (21%)
- Romanian (completely)
- Russian (completely)
- Spanish (completely)
- Turkish (completely)

If you’d like to help, you can proofread or translate strings here:
https://crowdin.com/project/groove-launcher

Best regards <3

**Comment by marcellotogg** [comment]
Great thanks

I will look at the translation system tomorrow.

Freundliche Grüsse
Marcel Tujetsch

-------- Ursprüngliche Nachricht --------
Am 17.11.24 21:09 um Berkay Tumal schrieb :

**Comment by marcellotogg** [comment]
Hi
I have translated a first batch of the texts. What else do I need to do? Or is the job done for me so far?

Best regards
Marcel Tujetsch

Sicher versendet mit [Proton Mail](https://proton.me/mail/home).

Berkay Tumal ***@***.***> schrieb am Sonntag, 17. November 2024 um 21:09:

**Comment by marcellotogg** [comment]
Hello
I have a question about the translation:
In German there are two different forms of Du (you), one informal (du) and one formal (sie).Do you want to address the users more informally (loosely)?

Best regards
Marcel Tujetsch

Sicher versendet mit [Proton Mail](https://proton.me/mail/home).

Berkay Tumal ***@***.***> schrieb am Sonntag, 17. November 2024 um 21:09:

**Comment by berkaytumal** [comment]
Hey
My German is only A2 so I didn't want to make an offer on that xD I checked my Windows Phone to review the system dialogs & texts and looks like it uses the formal you (Sie). Shall we go with Sie? Oh and yeah I saw your contributions ^^ Thanks a lot for them!

Oh and I'm asking this to anyone who is contributing by translating the locales. Are you translating in Hochdeutsch or are you translating a dialect of German?

Kind regards <3

**Comment by marcellotogg** [comment]
Hello
On the subject of formal/informal:
I have looked at various apps (launcher, browser, mail program). It looks like explanations are mostly made in direct address with Du, instructions are formulated neutrally with infinitives (see screenshot). That seems to make sense to me. If it suits you, I will go through all the texts again in this way.Second question: Of course the texts are in High German. There are far too many dialects to cover.

Regards
Marcel

Sicher versendet mit [Proton Mail](https://proton.me/mail/home).

[image.png]
Berkay Tumal ***@***.***> schrieb am Dienstag, 19. November 2024 um 08:13:

**Comment by berkaytumal** [comment]
I respect your decision, and like we dont have to go Windows Phone all the way so that's absolutely fine!

**Comment by marcellotogg** [comment]
Great thanks

Freundliche Grüsse
Marcel Tujetsch

-------- Ursprüngliche Nachricht --------
Am 19.11.24 15:53 um Berkay Tumal schrieb :

**Comment by marcellotogg** [comment]
Hello Berkay

I have looked through the texts again and used the discussed text form.
I am already looking forward to the next release.Good luck!

Kind regards

Marcel Tujetsch

Sicher versendet mit [Proton Mail](https://proton.me/mail/home).

Berkay Tumal ***@***.***> schrieb am Dienstag, 19. November 2024 um 15:53:

**Comment by KParthSingh** [comment]
I think this can be closed now.
